# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: atm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tatm.proto\"Q\n\x0fTransferRequest\x12\x17\n\x0f\x66rom_account_id\x18\x01 \x01(\x05\x12\x15\n\rto_account_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\"4\n\x10TransferResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2@\n\x0b\x42\x61nkService\x12\x31\n\x08Transfer\x12\x10.TransferRequest\x1a\x11.TransferResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFERREQUEST._serialized_start=13
  _TRANSFERREQUEST._serialized_end=94
  _TRANSFERRESPONSE._serialized_start=96
  _TRANSFERRESPONSE._serialized_end=148
  _BANKSERVICE._serialized_start=150
  _BANKSERVICE._serialized_end=214
# @@protoc_insertion_point(module_scope)
